In [1]:
import pandas as pd
cc_apps = pd.read_csv('cc_approvals.data', header = None)
cc_apps.head()

  0      1      2  3  4  5  6     7  8  9    10 11 12     13     14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t  1.0  f  g  00202    0.0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t  6.0  f  g  00043  560.0  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f  0.0  f  g  00280  824.0  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t  5.0  t  g  00100    3.0  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f  0.0  f  s  00120    0.0  +

In [2]:

cc_apps_description = cc_apps.describe()
print(cc_apps_description)

print('\n')

cc_apps_info = cc_apps.info()
print(cc_apps_info)

print('\n')

cc_apps.tail(17)

               2           7          10             14
count  690.000000  690.000000  690.00000     690.000000
mean     4.758725    2.223406    2.40000    1017.385507
std      4.978163    3.346513    4.86294    5210.102598
min      0.000000    0.000000    0.00000       0.000000
25%      1.000000    0.165000    0.00000       0.000000
50%      2.750000    1.000000    0.00000       5.000000
75%      7.207500    2.625000    3.00000     395.500000
max     28.000000   28.500000   67.00000  100000.000000


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       702 non-null    object
 1   1       691 non-null    object
 2   2       690 non-null    float64
 3   3       690 non-null    object
 4   4       690 non-null    object
 5   5       690 non-null    object
 6   6       690 non-null    object
 7   7       690 non-null    float64
 8   8       690 non-null    object
 9   9       690 non-null    object
 10  10      690 non-null    float64
 11  11      690 non-null    object
 12  12      690 non-null    object
 13  13      690 non-null    object
 14  14      690 non-null    float64
 15  15      690 non-null    object
dtypes: float64(4), object(12)
memory usage: 87.9+ KB
None

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
685,b,21.08,10.085,y,p,e,h,1.25,f,f,0.0,f,g,00260,0.0,-
686,a,22.67,0.750,u,g,c,v,2.00,f,t,2.0,t,g,00200,394.0,-
687,a,25.25,13.500,y,p,ff,ff,2.00,f,t,1.0,t,g,00200,1.0,-
688,b,17.92,0.205,u,g,aa,v,0.04,f,f,0.0,f,g,00280,750.0,-
689,b,35.00,3.375,u,g,c,h,8.29,f,f,0.0,t,g,00000,0.0,-
690,© 2022 GitHub,Inc.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
691,Terms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
692,Privacy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
693,Security,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
694,Status,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
695,Docs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
696,Contact GitHub,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
697,Pricing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
698,API,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
699,Training,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
700,Blog,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
701,About,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:

from sklearn.model_selection import train_test_split

cc_apps = cc_apps.drop([11,13], axis = 1
                      )

cc_apps_train, cc_apps_test = train_test_split(cc_apps,  test_size=0.33, random_state=42)

In [4]:

import numpy as np

cc_apps_train = cc_apps_train.replace('?', np.NaN)
cc_apps_test = cc_apps_test.replace('?', np.NaN)

In [5]:
cc_apps_train.fillna(cc_apps_train.mean(), inplace=True)
cc_apps_test.fillna(cc_apps_test, inplace=True)

print(cc_apps_train.isnull().sum())
print(cc_apps_test.isnull().sum())

0      7
1     12
2      0
3     13
4     13
5     14
6     14
7      0
8      7
9      7
10     0
12     7
14     0
15     7
dtype: int64
0      5
1     11
2      5
3      5
4      5
5      7
6      7
7      5
8      5
9      5
10     5
12     5
14     5
15     5
dtype: int64

C:\Users\mat_c\AppData\Local\Temp\ipykernel_19184\311386373.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  cc_apps_train.fillna(cc_apps_train.mean(), inplace=True)

In [6]:

for col in cc_apps_train.columns:

    if cc_apps_train[col].dtypes == 'object':

        cc_apps_train = cc_apps_train.fillna(cc_apps_train[col].value_counts().index[0])
        cc_apps_test = cc_apps_test.fillna(cc_apps_train[col].value_counts().index[0])

print(cc_apps_train.isnull().sum())

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
12    0
14    0
15    0
dtype: int64

In [7]:

cc_apps_train = pd.get_dummies(cc_apps_train)
cc_apps_test = pd.get_dummies(cc_apps_test)


cc_apps_test = cc_apps_test.reindex(columns=cc_apps_train.columns, fill_value=0)

In [8]:

from sklearn.preprocessing import MinMaxScaler

X_train, y_train = cc_apps_train.iloc[:, :-1].values, cc_apps_train.iloc[:, [-1]].values
X_test, y_test = cc_apps_test.iloc[:, :-1].values, cc_apps_test.iloc[:, [-1]].values

scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX_train = scaler.fit_transform(X_train)
rescaledX_test = scaler.transform(X_test)

In [17]:

from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(rescaledX_train, y_train.ravel())

LogisticRegression()

In [18]:

from sklearn.metrics import confusion_matrix

y_pred = logreg.predict(rescaledX_test)


print("Accuracy of logistic regression classifier: ", logreg.score(rescaledX_test,y_test))


confusion_matrix(y_test, y_pred)

Accuracy of logistic regression classifier:  1.0

array([[227,   0],
       [  0,   5]], dtype=int64)

In [19]:

from sklearn.model_selection import GridSearchCV

tol = [0.01, 0.001 ,0.0001]
max_iter = [100, 150, 200]


param_grid = dict(tol= tol, max_iter = max_iter)

In [22]:

grid_model = GridSearchCV(estimator=logreg, param_grid=param_grid, cv=5)

grid_model_result = grid_model.fit(rescaledX_train, y_train.ravel())


best_score, best_params = grid_model_result.best_score_, grid_model_result.best_params_
print("Best: %f using %s" % (best_score, best_params))


best_model = grid_model_result.best_estimator_
print("Accuracy of logistic regression classifier: ", best_model.score(rescaledX_test,y_test))

Best: 1.000000 using {'max_iter': 100, 'tol': 0.01}
Accuracy of logistic regression classifier:  1.0